# Generated by Django 5.2.8 on 2025-11-07 18:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_app', '0001_initial'),
        ('semester_app', '0001_initial'),
        ('subject_app', '0001_initial'),
        ('techskill_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_marks', models.PositiveIntegerField()),
                ('assignment_code', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='course_app.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='semester_app.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='subject_app.subject')),
                ('tech_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='techskill_app.techskill')),
            ],
        ),
    ]
